name: CI/CD Pipeline - ASP.NET Core

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'

        - name: Restore Dependencies
          run: dotnet restore

        - name: Build Project
          run:  dotnet build --no-restore

        # - name: Run Tests
        #   run:  dotnet test --no-build --verbosity normal

        - name: Publish the application
          run: dotnet publish BusTicketBookingSystem.csproj --configuration Release --output ./publish

        - name: Build Docker Image
          run: docker build -t karthikravi11/busticketapp:v1 .

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push Docker Image to DockerHub
          run: docker push karthikravi11/busticketapp:v1

